### ISSUE TITLE
I believe we Missing credentials , but please correct me if I mistaken

### ISSUE THREAD

**Issue by mikzuit** [form3tech-oss/interview-accountapi#12]
I solved this test few days ago (without this part below)   and still interested on how is possible to solve this line in your readme :

> The goal of this exercise is to write a client library in Go to access our fake account API service.

I strongly believe this is an issue of your test and you might be loosing candidates if i mistaken then i would be glad to understand better what you look for or a solution to your test. I thought what you ask was create a new service emulating the api packed in your docker image ( form3tech/interview-accountapi:v1.0.0-4-g63cf8434 ) . That's what my solution solve and test.

Since documentation to your api specifically says in :

 [https://api-docs.form3.tech/api.html#authentication](https://api-docs.form3.tech/api.html#authentication)

> "Base 64 encoding of client id:client secret"

Canditates should have credentials to send authentication and receive a token in a request like below ( "ZKIAJCF5UHCZBCKLCW5Q:da2f3f97a5014eceb574536e97652c56" of course are not real credentials: 

```
curl -X POST https://[local_ip]:[local_port]/v1/oauth2/token \
   -d grant_type=client_credentials \
   -u 'ZKIAJCF5UHCZBCKLCW5Q:da2f3f97a5014eceb574536e97652c56'
```

this would respond a token that candidates should send to "account" endpoints. 

If I mistaken I would like to know how you manage to , as described in readme,  "access our fake account API"  .

Thanks for your understanding.

**Comment by liamg** [comment]
> I thought what you ask was create a new service emulating the api packed in your docker image ( form3tech/interview-accountapi:v1.0.0-4-g63cf8434 ) . 

I'm afraid this is not what we ask for - we would like a client library to access the API in the docker image, we don't want a new service that emulates it.

To answer your question around credentials, whilst our "real" services do of course require authentication, no authentication is required to fire requests against the service running in the docker container we provide, which hopefully simplifies the exercise :)
