### ISSUE TITLE
API discrepancies?

### ISSUE THREAD

**Issue by martinreus** [form3tech-oss/interview-accountapi#23]
Hi! 

Please correct me if I am wrong: I have recently finished this exercise but noticed that even when testing the API using Postman with the example JSON payloads one can find in the documentation, some fields were ignored / not set. I believe that this could be caused by the fact that the last update for the Docker Hub container was done 6 months ago?

Anyhow, the fields I could not set with a POST (or read, with a GET) were `private_identification`, `organisation_identification` and `relationships`..

Thank you very much!

**Comment by martinreus-form3** [comment]
Update:

 - [ ] docs -> https://github.com/form3tech-oss/interview-accountapi/pull/27/files
 - [ ] accountapi implementation -> internal repo
 - [ ] accountapi example client -> internal repo
