### ISSUE TITLE
Non nominal cases for account delete

### ISSUE THREAD

**Issue by jeromedoucet** [form3tech-oss/interview-accountapi#30]
The API service provided for the test doesn't seems to have the expected behaviour on delete account for non nominal case.

- When the account doesn't exists, the returned code is 204 and not 404
- When the account does exists but the version doesn't match, a 404 is return (instead of a 409)

This is not a major issue, but it can be confusing when implementing integration tests cases for account deletion.

The tag of the image configured in the docker-compose at the moment of my test is `v1.0.0-4-g63cf8434`, but the behaviour seems to be the same on `latest`.

**Comment by martinreus-form3** [comment]
Verified the reported behaviour.
Fixing in internal repo.

**Comment by martinreus-form3** [comment]
Closing as fix was merged
