### ISSUE TITLE
Missing URL parameter in API documentation example requests

### ISSUE THREAD

**Issue by daniel-zullo** [form3tech-oss/interview-accountapi#47]
The `http`, `shell` and `python` example requests to delete an account in the API reference documentation does not include the URL parameter `version` and this parameter is required to delete an account.

See documentation https://api-docs.form3.tech/api.html?http#organisation-accounts-delete

HTTP Request documentation to delete an account
`DELETE /v1/organisation/accounts/{account.id}?version={version}`

Python example:
```python
import requests
requests.delete('https://api.form3.tech//v1/organisation/accounts/ad27e265-9605-4b4b-a0e5-3003ea9cc4dc')
```

Shell example:
```sh
curl -X DELETE https://api.form3.tech//v1/organisation/accounts/ad27e265-9605-4b4b-a0e5-3003ea9cc4dc
```

HTTP example:
```http
DELETE /v1/organisation/accounts/ad27e265-9605-4b4b-a0e5-3003ea9cc4dc HTTP/1.1
```

I didn't find how to report this minor issue directly in the API reference documentation so I reported  it here.

**Comment by jacoelho-form3** [comment]
Thanks for raising this issue.

Examples seem ok now.
